import type { APIRoute } from 'astro';

// ADR-0011 Consequences: "robots.txt is a GENERATED artifact of the SSG build, not a hand-edited
// file." A hand-edited robots.txt drifts from the decision it is supposed to express, and nobody
// re-reads it — this one is derived from the policy below, so changing the policy changes the file.
//
// The policy: ALLOW EVERY well-behaved crawler, training crawlers included.
//
// That was a reversal. The ADR originally blocked GPTBot, CCBot and Google-Extended, and the reasoning
// was sound — for an established publisher with negotiating leverage. WhyStack has none: no brand, no
// revenue, free content, and a primary problem of obscurity rather than theft. Blocking training
// crawlers would forfeit permanent presence inside the models developers actually ask, in exchange for
// protecting commodity knowledge that is already in every model from a thousand other sources.
//
// The moat is not the prose. It is the curation, the sequence, the roadmaps, the offline packs, the
// tools — none of which can be trained into a model.

const CRAWLERS: { agent: string; why: string }[] = [
  { agent: 'Googlebot', why: 'search indexing — primary' },
  { agent: 'Bingbot', why: 'search indexing — also feeds DuckDuckGo and parts of AI search' },
  { agent: 'YandexBot', why: 'search indexing' },
  { agent: 'OAI-SearchBot', why: 'ChatGPT Search — citation' },
  { agent: 'ChatGPT-User', why: 'user-triggered fetch — citation' },
  { agent: 'PerplexityBot', why: 'Perplexity — citation' },
  { agent: 'ClaudeBot', why: 'Claude web access — citation' },
  { agent: 'GPTBot', why: 'OpenAI model training — allowed deliberately (ADR-0011)' },
  { agent: 'CCBot', why: 'Common Crawl — feeds many models (ADR-0011)' },
  { agent: 'Google-Extended', why: 'Gemini training — allowed deliberately (ADR-0011)' },
  { agent: 'Applebot-Extended', why: 'Apple model training — allowed deliberately (ADR-0011)' },
];

/** Never public, for any crawler. Content that has not passed human review does not exist. */
const NEVER_PUBLIC = ['/draft/', '/admin/', '/editorial/', '/api/'];

export const GET: APIRoute = ({ site }) => {
  const lines: string[] = [
    '# Generated by apps/site. Do not edit — edit the policy in src/pages/robots.txt.ts.',
    '# Policy: ADR-0011 (Discoverability and AI Crawler Policy) — allow all well-behaved crawlers.',
    '',
  ];

  for (const { agent, why } of CRAWLERS) {
    lines.push(`# ${why}`);
    lines.push(`User-agent: ${agent}`);
    lines.push('Allow: /');
    lines.push('');
  }

  lines.push('User-agent: *');
  lines.push('Allow: /');
  for (const path of NEVER_PUBLIC) {
    lines.push(`Disallow: ${path}`);
  }
  lines.push('');

  if (site) {
    lines.push(`Sitemap: ${new URL('sitemap-index.xml', site).href}`);
  }

  return new Response(lines.join('\n'), {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
