// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhyStack.Infrastructure.Persistence;

#nullable disable

namespace WhyStack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WhyStackDbContext))]
    [Migration("20260716111135_Schema_Progress_And_Streak")]
    partial class Schema_Progress_And_Streak
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhyStack.Domain.Content.Ecosystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Ecosystems_Key");

                    b.ToTable("Ecosystems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d73a6477-bb02-d027-a6dc-2a4e6a6a8cd3"),
                            IsAvailable = true,
                            Key = "dotnet",
                            Name = ".NET",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("6c850f94-241d-6842-9f25-56f156664b3b"),
                            IsAvailable = false,
                            Key = "java",
                            Name = "Java",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("3760f81d-ea8c-e777-1e84-ea538c3db9e2"),
                            IsAvailable = false,
                            Key = "nodejs",
                            Name = "Node.js",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("fc096d90-aa39-9c31-9e65-e3249a824757"),
                            IsAvailable = false,
                            Key = "php",
                            Name = "PHP",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Content.ImplementationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionTypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TopicImplementationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionTypeKey");

                    b.HasIndex("TopicImplementationId", "SectionTypeKey", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ImplementationSections_Impl_Type_Language");

                    b.ToTable("ImplementationSections", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.KnowledgeDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_KnowledgeDomains_Key");

                    b.ToTable("KnowledgeDomains", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("58c93303-459d-b159-502a-459be534f867"),
                            Key = "backend",
                            Name = "Backend",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("2e6c62e8-a477-c23e-727a-91dd900d508f"),
                            Key = "database",
                            Name = "Database",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("4f8a0a68-63fa-4dcd-3484-78fb4b313db1"),
                            Key = "language",
                            Name = "Language",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a57963e8-a284-9bf6-a395-515b9433e05b"),
                            Key = "architecture",
                            Name = "Architecture",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b8273c4a-efd0-6ad5-cdf1-10e32e043cde"),
                            Key = "networking",
                            Name = "Networking",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("41d1d484-6405-0257-9a57-09ca5202b61f"),
                            Key = "devops",
                            Name = "DevOps",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("ff40d5ba-3651-4265-b3e4-18e58f3315c5"),
                            Key = "security",
                            Name = "Security",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("bca126a8-66cc-f22b-336c-55b8874036d4"),
                            Key = "testing",
                            Name = "Testing",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Content.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FenceLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EcosystemId");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_ProgrammingLanguages_Key");

                    b.ToTable("ProgrammingLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("128dfb6e-1771-c105-c27e-88747e70e54f"),
                            EcosystemId = new Guid("d73a6477-bb02-d027-a6dc-2a4e6a6a8cd3"),
                            FenceLanguage = "csharp",
                            Key = "csharp",
                            Name = "C#",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a0fc966a-22ed-5b5a-e855-fc159eef61f6"),
                            EcosystemId = new Guid("d73a6477-bb02-d027-a6dc-2a4e6a6a8cd3"),
                            FenceLanguage = "fsharp",
                            Key = "fsharp",
                            Name = "F#",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("61a54f6c-6267-a8b5-41b0-285f50a02567"),
                            EcosystemId = new Guid("6c850f94-241d-6842-9f25-56f156664b3b"),
                            FenceLanguage = "java",
                            Key = "java",
                            Name = "Java",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("c8d22ab9-aec5-bb09-15aa-0d3cbdd95d6e"),
                            EcosystemId = new Guid("6c850f94-241d-6842-9f25-56f156664b3b"),
                            FenceLanguage = "kotlin",
                            Key = "kotlin",
                            Name = "Kotlin",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("010eea63-f2fe-3d81-314f-39914463faa0"),
                            EcosystemId = new Guid("3760f81d-ea8c-e777-1e84-ea538c3db9e2"),
                            FenceLanguage = "ts",
                            Key = "typescript",
                            Name = "TypeScript",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("d18f51dd-dc11-50c2-9b18-5fc098cd0643"),
                            EcosystemId = new Guid("3760f81d-ea8c-e777-1e84-ea538c3db9e2"),
                            FenceLanguage = "js",
                            Key = "javascript",
                            Name = "JavaScript",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("3d39160c-beaa-0258-c8bf-4bdf1e504ce4"),
                            EcosystemId = new Guid("fc096d90-aa39-9c31-9e65-e3249a824757"),
                            FenceLanguage = "php",
                            Key = "php",
                            Name = "PHP",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Content.SectionType", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsGraphDerived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("SectionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Summary",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 1
                        },
                        new
                        {
                            Key = "LearningObjectives",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 2
                        },
                        new
                        {
                            Key = "WhyThisTopicMatters",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 3
                        },
                        new
                        {
                            Key = "Prerequisites",
                            IsGraphDerived = true,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 4
                        },
                        new
                        {
                            Key = "Definition",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 5
                        },
                        new
                        {
                            Key = "WhyItExists",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 6
                        },
                        new
                        {
                            Key = "ProblemItSolves",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 7
                        },
                        new
                        {
                            Key = "HistoricalContext",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 8
                        },
                        new
                        {
                            Key = "CoreMentalModel",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 9
                        },
                        new
                        {
                            Key = "CoreConcepts",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 10
                        },
                        new
                        {
                            Key = "InternalMechanics",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Implementation",
                            SortOrder = 11
                        },
                        new
                        {
                            Key = "Syntax",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Implementation",
                            SortOrder = 12
                        },
                        new
                        {
                            Key = "BasicExample",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Implementation",
                            SortOrder = 13
                        },
                        new
                        {
                            Key = "ProgressiveExamples",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Implementation",
                            SortOrder = 14
                        },
                        new
                        {
                            Key = "RealWorldScenario",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 15
                        },
                        new
                        {
                            Key = "ArchitectureContext",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 16
                        },
                        new
                        {
                            Key = "PerformanceConsiderations",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 17
                        },
                        new
                        {
                            Key = "SecurityConsiderations",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 18
                        },
                        new
                        {
                            Key = "TestingConsiderations",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 19
                        },
                        new
                        {
                            Key = "BestPractices",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 20
                        },
                        new
                        {
                            Key = "CommonMistakes",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 21
                        },
                        new
                        {
                            Key = "TradeOffs",
                            IsGraphDerived = false,
                            IsMandatory = true,
                            Scope = "Concept",
                            SortOrder = 22
                        },
                        new
                        {
                            Key = "Alternatives",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 23
                        },
                        new
                        {
                            Key = "VersionNotes",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Implementation",
                            SortOrder = 24
                        },
                        new
                        {
                            Key = "InterviewQuestions",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 25
                        },
                        new
                        {
                            Key = "Quiz",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 26
                        },
                        new
                        {
                            Key = "RelatedTopics",
                            IsGraphDerived = true,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 27
                        },
                        new
                        {
                            Key = "NextRecommendedTopic",
                            IsGraphDerived = true,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 28
                        },
                        new
                        {
                            Key = "FurtherReading",
                            IsGraphDerived = false,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 29
                        },
                        new
                        {
                            Key = "Glossary",
                            IsGraphDerived = true,
                            IsMandatory = false,
                            Scope = "Concept",
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Content.SubArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_SubAreas_Key");

                    b.ToTable("SubAreas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("561d4f29-1a71-6548-7959-17d7fbff9bbb"),
                            Key = "async",
                            Name = "Async / Await",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("fde9c505-0ab1-4f6f-8923-b4044e0c3f93"),
                            Key = "memory-management",
                            Name = "Bellek Yönetimi",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b8c01adc-9a89-7d1f-c664-04c6f4b9b0c2"),
                            Key = "collections",
                            Name = "Koleksiyonlar",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("c1a104fa-41f9-69b9-8219-e33937fe5648"),
                            Key = "error-handling",
                            Name = "Hata Yönetimi",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("2d97c76f-2856-c65c-c93b-f5242a330196"),
                            Key = "dependency-injection",
                            Name = "Dependency Injection",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("c92cdedb-7d89-b251-5546-f3cd387e1be1"),
                            Key = "concurrency",
                            Name = "Eşzamanlılık",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ForbiddenTranslations")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique()
                        .HasDatabaseName("UX_Terms_Text");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TermExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_TermExplanations_TermId_LanguageCode");

                    b.ToTable("TermExplanations", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DefaultTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SubAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Topics_Slug");

                    b.HasIndex("StableKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Topics_StableKey");

                    b.HasIndex("DomainId", "DefaultLevel")
                        .HasDatabaseName("IX_Topics_DomainId_DefaultLevel");

                    b.HasIndex("SubAreaId", "DefaultLevel")
                        .HasDatabaseName("IX_Topics_SubAreaId_DefaultLevel")
                        .HasFilter("[SubAreaId] IS NOT NULL");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcosystemKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("TopicVersionId", "LanguageCode", "Order")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicBlocks_Version_Language_Order");

                    b.ToTable("TopicBlocks", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicImplementation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgrammingLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportedVersions")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EcosystemId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.HasIndex("TopicVersionId", "EcosystemId")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicImplementations_TopicVersionId_EcosystemId");

                    b.ToTable("TopicImplementations", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("ToTopicId")
                        .HasDatabaseName("IX_TopicRelationships_ToTopicId");

                    b.HasIndex("FromTopicId", "ToTopicId", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicRelationships_From_To_Type");

                    b.ToTable("TopicRelationships", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TopicVersionId")
                        .HasDatabaseName("IX_TopicReviews_TopicVersionId");

                    b.ToTable("TopicReviews", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionTypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SectionTypeKey");

                    b.HasIndex("TopicVersionId", "SectionTypeKey", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicSections_Version_Type_Language");

                    b.ToTable("TopicSections", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSupportedVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("TopicVersionId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicSupportedVersions_TopicVersionId_Version");

                    b.ToTable("TopicSupportedVersions", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Summary")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TopicVersionId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicTranslations_TopicVersionId_LanguageCode");

                    b.ToTable("TopicTranslations", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedReadingMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastReviewedOn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicVersions_TopicId_VersionNumber");

                    b.ToTable("TopicVersions", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_EmailConfirmationTokens_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("EmailConfirmationTokens", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_PasswordResetTokens_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_NormalizedName");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Not signed in. May read published content.",
                            IsSystemRole = true,
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Signed in. May learn, track progress and bookmark.",
                            IsSystemRole = true,
                            Name = "RegisteredUser",
                            NormalizedName = "REGISTEREDUSER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reserved for a future tier. Grants nothing today (ADR-0005, ADR-0012).",
                            IsSystemRole = true,
                            Name = "PremiumUser",
                            NormalizedName = "PREMIUMUSER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dormant. Will author and edit content.",
                            IsSystemRole = true,
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dormant. Will review content before publication.",
                            IsSystemRole = true,
                            Name = "Reviewer",
                            NormalizedName = "REVIEWER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dormant. Will translate content.",
                            IsSystemRole = true,
                            Name = "Translator",
                            NormalizedName = "TRANSLATOR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full administrative access.",
                            IsSystemRole = true,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail")
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserLoginEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddressHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UserLoginEvents_Email_CreatedAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UserLoginEvents_UserId_CreatedAtUtc");

                    b.ToTable("UserLoginEvents", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddressHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_UserSessions_FamilyId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_UserSessions_RefreshTokenHash");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("IX_UserSessions_UserId_RevokedAtUtc");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ContentLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredSkillLevel")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("ReadingFontScale")
                        .HasColumnType("float");

                    b.Property<bool>("ReducedMotionEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserPreferences_UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserStreak", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastActiveOn")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserStreaks", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserTopicProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EcosystemKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LastBlockOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId", "UpdatedAtUtc")
                        .HasDatabaseName("IX_UserTopicProgress_UserId_UpdatedAtUtc");

                    b.HasIndex("UserId", "TopicId", "EcosystemKey")
                        .IsUnique()
                        .HasDatabaseName("UX_UserTopicProgress_User_Topic_Ecosystem")
                        .HasFilter("[EcosystemKey] IS NOT NULL");

                    b.ToTable("UserTopicProgress", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.ImplementationSection", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.SectionType", null)
                        .WithMany()
                        .HasForeignKey("SectionTypeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.TopicImplementation", "Implementation")
                        .WithMany("Sections")
                        .HasForeignKey("TopicImplementationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Implementation");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.ProgrammingLanguage", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Ecosystem", "Ecosystem")
                        .WithMany("Languages")
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecosystem");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TermExplanation", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Term", null)
                        .WithMany("Explanations")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Topic", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.KnowledgeDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.SubArea", "SubArea")
                        .WithMany()
                        .HasForeignKey("SubAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Domain");

                    b.Navigation("SubArea");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicBlock", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.TopicVersion", "TopicVersion")
                        .WithMany("Blocks")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicVersion");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicImplementation", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Ecosystem", "Ecosystem")
                        .WithMany()
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.ProgrammingLanguage", null)
                        .WithMany()
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WhyStack.Domain.Content.TopicVersion", "TopicVersion")
                        .WithMany("Implementations")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecosystem");

                    b.Navigation("TopicVersion");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicRelationship", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Topic", "FromTopic")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("FromTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.Topic", "ToTopic")
                        .WithMany()
                        .HasForeignKey("ToTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromTopic");

                    b.Navigation("ToTopic");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicReview", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.TopicVersion", null)
                        .WithMany()
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSection", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.SectionType", null)
                        .WithMany()
                        .HasForeignKey("SectionTypeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.TopicVersion", "TopicVersion")
                        .WithMany("Sections")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicVersion");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSupportedVersion", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.TopicVersion", null)
                        .WithMany("SupportedVersions")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicTranslation", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.TopicVersion", "TopicVersion")
                        .WithMany("Translations")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicVersion");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicVersion", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Topic", "Topic")
                        .WithMany("Versions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.EmailConfirmationToken", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserPreferences", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserStreak", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("WhyStack.Domain.Users.UserStreak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserTopicProgress", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Ecosystem", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Term", b =>
                {
                    b.Navigation("Explanations");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Topic", b =>
                {
                    b.Navigation("OutgoingRelationships");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicImplementation", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicVersion", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Implementations");

                    b.Navigation("Sections");

                    b.Navigation("SupportedVersions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
