// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhyStack.Infrastructure.Persistence;

#nullable disable

namespace WhyStack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WhyStackDbContext))]
    [Migration("20260713214051_Schema_Content")]
    partial class Schema_Content
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhyStack.Domain.Content.SectionType", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsGraphDerived")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("SectionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Summary",
                            IsGraphDerived = false,
                            SortOrder = 1
                        },
                        new
                        {
                            Key = "LearningObjectives",
                            IsGraphDerived = false,
                            SortOrder = 2
                        },
                        new
                        {
                            Key = "WhyThisTopicMatters",
                            IsGraphDerived = false,
                            SortOrder = 3
                        },
                        new
                        {
                            Key = "Prerequisites",
                            IsGraphDerived = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Key = "Definition",
                            IsGraphDerived = false,
                            SortOrder = 5
                        },
                        new
                        {
                            Key = "WhyItExists",
                            IsGraphDerived = false,
                            SortOrder = 6
                        },
                        new
                        {
                            Key = "ProblemItSolves",
                            IsGraphDerived = false,
                            SortOrder = 7
                        },
                        new
                        {
                            Key = "HistoricalContext",
                            IsGraphDerived = false,
                            SortOrder = 8
                        },
                        new
                        {
                            Key = "CoreMentalModel",
                            IsGraphDerived = false,
                            SortOrder = 9
                        },
                        new
                        {
                            Key = "CoreConcepts",
                            IsGraphDerived = false,
                            SortOrder = 10
                        },
                        new
                        {
                            Key = "InternalMechanics",
                            IsGraphDerived = false,
                            SortOrder = 11
                        },
                        new
                        {
                            Key = "Syntax",
                            IsGraphDerived = false,
                            SortOrder = 12
                        },
                        new
                        {
                            Key = "BasicExample",
                            IsGraphDerived = false,
                            SortOrder = 13
                        },
                        new
                        {
                            Key = "ProgressiveExamples",
                            IsGraphDerived = false,
                            SortOrder = 14
                        },
                        new
                        {
                            Key = "RealWorldScenario",
                            IsGraphDerived = false,
                            SortOrder = 15
                        },
                        new
                        {
                            Key = "ArchitectureContext",
                            IsGraphDerived = false,
                            SortOrder = 16
                        },
                        new
                        {
                            Key = "PerformanceConsiderations",
                            IsGraphDerived = false,
                            SortOrder = 17
                        },
                        new
                        {
                            Key = "SecurityConsiderations",
                            IsGraphDerived = false,
                            SortOrder = 18
                        },
                        new
                        {
                            Key = "TestingConsiderations",
                            IsGraphDerived = false,
                            SortOrder = 19
                        },
                        new
                        {
                            Key = "BestPractices",
                            IsGraphDerived = false,
                            SortOrder = 20
                        },
                        new
                        {
                            Key = "CommonMistakes",
                            IsGraphDerived = false,
                            SortOrder = 21
                        },
                        new
                        {
                            Key = "TradeOffs",
                            IsGraphDerived = false,
                            SortOrder = 22
                        },
                        new
                        {
                            Key = "Alternatives",
                            IsGraphDerived = false,
                            SortOrder = 23
                        },
                        new
                        {
                            Key = "VersionNotes",
                            IsGraphDerived = false,
                            SortOrder = 24
                        },
                        new
                        {
                            Key = "InterviewQuestions",
                            IsGraphDerived = false,
                            SortOrder = 25
                        },
                        new
                        {
                            Key = "Quiz",
                            IsGraphDerived = false,
                            SortOrder = 26
                        },
                        new
                        {
                            Key = "RelatedTopics",
                            IsGraphDerived = true,
                            SortOrder = 27
                        },
                        new
                        {
                            Key = "NextRecommendedTopic",
                            IsGraphDerived = true,
                            SortOrder = 28
                        },
                        new
                        {
                            Key = "FurtherReading",
                            IsGraphDerived = false,
                            SortOrder = 29
                        },
                        new
                        {
                            Key = "Glossary",
                            IsGraphDerived = true,
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DefaultTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Topics_Slug");

                    b.HasIndex("StableKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Topics_StableKey");

                    b.HasIndex("Technology", "DefaultLevel")
                        .HasDatabaseName("IX_Topics_Technology_DefaultLevel");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("ToTopicId")
                        .HasDatabaseName("IX_TopicRelationships_ToTopicId");

                    b.HasIndex("FromTopicId", "ToTopicId", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicRelationships_From_To_Type");

                    b.ToTable("TopicRelationships", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectionTypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionTypeKey");

                    b.HasIndex("TopicVersionId", "SectionTypeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicSections_TopicVersionId_SectionTypeKey");

                    b.ToTable("TopicSections", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSupportedVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("TopicVersionId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicSupportedVersions_TopicVersionId_Version");

                    b.ToTable("TopicSupportedVersions", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MarkdownPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TopicVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TopicVersionId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicTranslations_TopicVersionId_LanguageCode");

                    b.ToTable("TopicTranslations", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedReadingMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastReviewedOn")
                        .HasColumnType("date");

                    b.Property<string>("MarkdownPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_TopicVersions_TopicId_VersionNumber");

                    b.ToTable("TopicVersions", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_EmailConfirmationTokens_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("EmailConfirmationTokens", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_PasswordResetTokens_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_NormalizedName");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Not signed in. May read published content.",
                            IsSystemRole = true,
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Signed in. May learn, track progress and bookmark.",
                            IsSystemRole = true,
                            Name = "RegisteredUser",
                            NormalizedName = "REGISTEREDUSER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reserved for a future tier. Grants nothing today (ADR-0005, ADR-0012).",
                            IsSystemRole = true,
                            Name = "PremiumUser",
                            NormalizedName = "PREMIUMUSER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dormant. Will author and edit content.",
                            IsSystemRole = true,
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dormant. Will review content before publication.",
                            IsSystemRole = true,
                            Name = "Reviewer",
                            NormalizedName = "REVIEWER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dormant. Will translate content.",
                            IsSystemRole = true,
                            Name = "Translator",
                            NormalizedName = "TRANSLATOR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full administrative access.",
                            IsSystemRole = true,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail")
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserLoginEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IpAddressHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UserLoginEvents_Email_CreatedAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UserLoginEvents_UserId_CreatedAtUtc");

                    b.ToTable("UserLoginEvents", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddressHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_UserSessions_FamilyId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_UserSessions_RefreshTokenHash");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("IX_UserSessions_UserId_RevokedAtUtc");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ContentLanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredSkillLevel")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("ReadingFontScale")
                        .HasColumnType("float");

                    b.Property<bool>("ReducedMotionEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserPreferences_UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicRelationship", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Topic", "FromTopic")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("FromTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.Topic", "ToTopic")
                        .WithMany()
                        .HasForeignKey("ToTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromTopic");

                    b.Navigation("ToTopic");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSection", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.SectionType", null)
                        .WithMany()
                        .HasForeignKey("SectionTypeKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Content.TopicVersion", "TopicVersion")
                        .WithMany("Sections")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicVersion");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicSupportedVersion", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.TopicVersion", null)
                        .WithMany("SupportedVersions")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicTranslation", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.TopicVersion", "TopicVersion")
                        .WithMany("Translations")
                        .HasForeignKey("TopicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicVersion");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicVersion", b =>
                {
                    b.HasOne("WhyStack.Domain.Content.Topic", "Topic")
                        .WithMany("Versions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.EmailConfirmationToken", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhyStack.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Users.UserPreferences", b =>
                {
                    b.HasOne("WhyStack.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhyStack.Domain.Content.Topic", b =>
                {
                    b.Navigation("OutgoingRelationships");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WhyStack.Domain.Content.TopicVersion", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("SupportedVersions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("WhyStack.Domain.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
